name: ppo
gae_lambda: 0.95
clip_epsilon: 0.2
entropy_coeff: 0.0
val_coeff: 0.5
aux_coeff: 0.2
task_coeff: 1.0
intr_coeff: 0.0
target_kl: null
max_grad_norm: 0.5

lr: 3e-4
n_iterations: 100
max_steps: 512
num_steps: 256
n_epochs: 2
save_interval: 10
mini_batch_size: 128

# Recurrent PPO
num_layers: 2

# minibatch_size needs to be able to divide num_envs
minibatch_size: 64
