defaults:
  - algorithm: ppo
  - env: base_env
  - model: base_model
  - _self_

wandb:
  project: semproj
  entity: eazevedo-eth-z-rich
  group: test        
  tags: [ppo]
  mode: online       # online | offline | disabled

seed: 42




