defaults:
  - algorithm: recurrent_ppo
  - env: base_env
  - model: base_model
  - observation: mlp_observation
  - backbone: lstm_backbone
  - head: base_head
  - _self_

wandb:
  project: semproj
  entity: eazevedo-eth-z-rich
  group: test        
  tags: [ppo]
  mode: online       # online | offline | disabled

seed: 42




