defaults:
  - algorithm: ppo
  - env: easy_env
  - observation: mlp_observation
  - backbone: mlp_backbone
  - head: base_head
  - _self_

wandb:
  project: semproj
  entity: eazevedo-eth-z-rich
  group: test        
  tags: [ppo]
  mode: online       # online | offline | disabled

seed: 42




