defaults:
  - env: traj_gen_env
  - _self_

wandb:
  project: semproj
  entity: eazevedo-eth-z-rich
  group: test        
  tags: [ppo]
  mode: online       # online | offline | disabled

seed: 42
place_cell_size: 256
head_dir_cell_size: 12
sigma_c: 10  # 0.01m (Banino Table 1 sigma^(c)) * 1000 units/m
kappa: 20
nr_iterations: 42857
block_size: 100
lr: 1e-5

clip_tresh: 1e-5
momentum: 0.9
decay: 1e-5




