name: "NavEnv"
room_path: "rooms/test_room.json"

num_classes: 3
act_dim: 2
action_low: -1
action_high: 1

max_speed: 13.0
range_type: diagonal 
ray_density: 0.2
fov: 180

ray_encoding: 7
proprio_dim: 2

rand_pos: "True"

num_envs: 256
num_eval_envs: 50     # parallel episodes rolled out per evaluate_policy() call
gamma: 0.99
goal_radius: 4.0      # distance threshold to count as reaching the goal

completion_rate_eps: 10
mean_of_means_runs: 10
